### ISSUE TITLE
关于插件初始化相关问题

### ISSUE THREAD

**Issue by doublezhuang101** [Wmj520/MYQQ_SDK_CPP#1]
在阅读了MQdemo.cpp后，大致了解了开发逻辑，我已经能够对好友消息以及群消息进行处理等操作，我现在想将部分数据在插件启动时读入内存，例如一个含有QQ号的string容器在插件启动时读入内存，在后续消息时候直接使用，只用读入一次，而不是消息来后再重新读入。想请教一下插件启动时候会运行的代码块如何编写。

**Comment by Wmj520** [comment]
MYQQ框架几乎将所有插件事件都封装在MQ_Event函数中(本SDK使用**Event::reg_Event**向该事件注册回调函数)，不仅包括好友消息、群消息等QQ事件，还囊括了插件载入、插件启用等插件事件。
若需要在插件载入或启用时，只需要再用**Event::reg_Event**注册新的回调函数，并用**MQEventCheck**宏分割事件。
下面贴一段你可能需要的代码
`
Event::reg_Event([](const Event::NormalEvent& e) {
		MQEventCheck(e.eventType, Enum::MQEventEnum::消息类型_本插件载入) //消息类型_插件被启用
		{
                        static bool containInit = false;
                        if(containInit)return;
                        contain.init();
		}
	}, 10000);
`

**Comment by Wmj520** [comment]
还有一种方法，即在MQ_REGISTER_EVENT的作用域内添加你的容器初始化代码，该作用域内的事件会发生于插件载入、api函数初始化后，其他事件之前。

**Comment by Wmj520** [comment]
> 在阅读了MQdemo.cpp后，大致了解了开发逻辑，我已经能够对好友消息以及群消息进行处理等操作，我现在想将部分数据在插件启动时读入内存，例如一个含有QQ号的string容器在插件启动时读入内存，在后续消息时候直接使用，只用读入一次，而不是消息来后再重新读入。想请教一下插件启动时候会运行的代码块如何编写。

MYQQ框架几乎将所有插件事件都封装在MQ_Event函数中(本SDK使用Event::reg_Event向该事件注册回调函数)，不仅包括好友消息、群消息等QQ事件，还囊括了插件载入、插件启用等插件事件。
若需要在插件载入或启用时，只需要再用Event::reg_Event注册新的回调函数，并用MQEventCheck宏分割事件。
下面贴一段你可能需要的代码
`Event::reg_Event([](const Event::NormalEvent& e) { MQEventCheck(e.eventType, Enum::MQEventEnum::消息类型_本插件载入) //消息类型_插件被启用 { static bool containInit = false; if(containInit)return; contain.init(); } }, 10000);`
还有一种方法，即在MQ_REGISTER_EVENT的作用域内添加你的容器初始化代码，该作用域内的事件会发生于插件载入、api函数初始化后，其他事件之前，且只发生一次。

**Comment by doublezhuang101** [comment]
我通过您介绍的第一种方式来进行尝试实现初始化的程度，并未奏效，似乎这部分代码块并未被运行，因为我未能看见框架输出fun。
`	Event::reg_Event([](const Event::NormalEvent& e) {
		MQEventCheck(e.eventType, Enum::MQEventEnum::消息类型_本插件载入)
		{
			Api::FrameAPI::OutPut("fun");
			InitQQ(QQnum);
			InitIDcard(IDname);
			Save_data(QQnum, IDname);
		}
		}, 10000);`
但是我通过在MQ_REGISTER_EVENT的作用域内添加我的初始化函数成功奏效，解决了这一问题。

**Comment by Wmj520** [comment]
还有一种写法是在

> 我通过您介绍的第一种方式来进行尝试实现初始化的程度，并未奏效，似乎这部分代码块并未被运行，因为我未能看见框架输出fun。 ` Event::reg_Event([](const Event::NormalEvent& e) { MQEventCheck(e.eventType, Enum::MQEventEnum::消息类型_本插件载入) { Api::FrameAPI::OutPut("fun"); InitQQ(QQnum); InitIDcard(IDname); Save_data(QQnum, IDname); } }, 10000);` 但是我通过在MQ_REGISTER_EVENT的作用域内添加我的初始化函数成功奏效，解决了这一问题。

我刚从头看了下代码，本SDK对插件启用、插件载入事件会即刻返回，不执行回调函数，关于该问题会在后一版本解决，亦或者你可以在src/MQcore/MQEvent.cpp文件中修改152-163行的内容。

**Comment by Wmj520** [comment]
> 我通过您介绍的第一种方式来进行尝试实现初始化的程度，并未奏效，似乎这部分代码块并未被运行，因为我未能看见框架输出fun。 ` Event::reg_Event([](const Event::NormalEvent& e) { MQEventCheck(e.eventType, Enum::MQEventEnum::消息类型_本插件载入) { Api::FrameAPI::OutPut("fun"); InitQQ(QQnum); InitIDcard(IDname); Save_data(QQnum, IDname); } }, 10000);` 但是我通过在MQ_REGISTER_EVENT的作用域内添加我的初始化函数成功奏效，解决了这一问题。

我刚从头看了下代码，本SDK对插件启用、插件载入事件会即刻返回，不执行回调函数，关于该问题会在后一版本解决，亦或者你可以在src/MQcore/MQEvent.cpp文件中修改152-163行的内容。

**Comment by doublezhuang101** [comment]
> > 我通过您介绍的第一种方式来进行尝试实现初始化的程度，并未奏效，似乎这部分代码块并未被运行，因为我未能看见框架输出fun。 ` Event::reg_Event([](const Event::NormalEvent& e) { MQEventCheck(e.eventType, Enum::MQEventEnum::消息类型_本插件载入) { Api::FrameAPI::OutPut("fun"); InitQQ(QQnum); InitIDcard(IDname); Save_data(QQnum, IDname); } }, 10000);` 但是我通过在MQ_REGISTER_EVENT的作用域内添加我的初始化函数成功奏效，解决了这一问题。
> 
> 我刚从头看了下代码，本SDK对插件启用、插件载入事件会即刻返回，不执行回调函数，关于该问题会在后一版本解决，亦或者你可以在src/MQcore/MQEvent.cpp文件中修改152-163行的内容。

非常感谢您的回答，对我十分有帮助，我的问题在现有框架下得到了解决方案。
